apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: device-secret-1-10-202303-003
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: gcp-secrets-manager
    kind: ClusterSecretStore
  target:
    name: device-secret-1-10-202303-003
    creationPolicy: Owner
  data:
  - secretKey: tmsID
    remoteRef:
      key: device-1-10-202303-003-tmsID
  - secretKey: thingCert
    remoteRef:
      key: device-1-10-202303-003-thingCert
  - secretKey: privateKey
    remoteRef:
      key: device-1-10-202303-003-privateKey